language:
  - php
  - c

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6



before_script:
  - composer install --dev
 - git submodule --quiet update --init --recursive
 - (cd build; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && sudo ./configure --enable-smceframework && make && sudo make install)
 - ulimit -c unlimited || true

